# Programación y NumPy

En la primera parte de este notebook se exploran algunos temas de programación. En la segunda parte se empieza a trabajar con NumPy.

## 1. Programación

### 1.1 Operaciones Lógicas

La operación `not` es simplemente la negación del booleano.

In [10]:
variable_1 = True
print(not(variable_1))

variable_2 = False
print(not(variable_2))

False
True


La operación `and` devuelve **True** únicamente cuando ambas variables son verdaderas. Experimentar con la celda inferior y comprobar su tabla de verdad.

In [11]:
variable_1 = True
variable_2 = False
print(variable_1 and variable_2)

False


<font color='mediumblue'>**Ejercicio:**</font> comprobar la tabla de verdad de la operación `or` jugando con la celda siguiente.

In [15]:
A = False
B = False
A_or_B = variable_1 or variable_2
print(A_or_B)

True


### 1.2 Estructuras de control - Condicionales

Los condicionales permiten ejecutar o no un bloque de codigo dependiendo de ciertas condiciones. "Si se cumple esta condición, hace A. Si no se cumple, hace B". B puede ser: hacer algo o no hacer nada.

### 1.2.1 If

El condicional más simple es el `if`. Para mayor claridad escribiremos la condicion entre parentesis (), aunque esto no es necesario.

Estructura:

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
```

Ejemplos:

In [16]:
valor = 15
if (valor > 10):
    print('El valor es mayor que 10')

El valor es mayor que 10


Prestar atención a que la condición debe ser un booleano

In [17]:
print(valor > 10)
print(type(valor > 10))

True
<class 'bool'>


**Nota:** para comparar variables se usan: menor `<`, mayor `>`, igualdad `==`, menor o igual  `<=`, y mayor o igual `>=`. Distinto: "!=" 

In [18]:
print(3 == 3)
print(3 <= 3)
print(3 >= 3)

True
True
True


### 1.2.2 If, Else

A la estrucutra con `if` se le puede agregar otro bloque de codigo que se ejecute si la condición exigida NO se cumple. Esto se logra mediante la expresión `else`.

Estructura:

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
else:
    Si NO se cumple la condición, se ejecutan estas líneas de código
```

In [19]:
nombre = 'Pedro'

if (nombre == 'Juan'):
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

Esta persona NO se llama Juan


Nuevamente ver que la condición - lo que está entre paréntesis - es un booleano.

In [20]:
# Verificación
'Juan'=='Pedro'

False

### 1.2.3 If, Elif, Else
A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desee, mediante la expresión `elif`. El orden en que se van chequeando las condiciones depende de su posición, priemero se chequea el `if`, luego el primer `elif`, luego el segundo, y así sucesivamente.

Estructura:

``` python
if condicion_1:
    Si se cumple la condicion_1 , se ejecutan estas líneas de código
elif condicion_2:
    Si se cumple la condicion_2 , se ejecutan estas líneas de código
elif condicion_3:
    Si se cumple la condicion_3 , se ejecutan estas líneas de código
else:
    Si NO se cumple ninguna de las condiciones anteriores, se ejecutan líneas celdas de código
```


In [21]:
edad = 20

if (edad < 18):
    print('Esta persona tiene menos de 18 años')
elif (edad > 18):
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

Esta persona tiene mas de 18 años


<font color='mediumblue'>**Ejercicio:**</font> Escriba un bloque de código que, dado un número, imprima la frase "El numero es par" si el número es par o la frase "El numero es impar" si no lo es.

In [22]:
numero = 16

if numero%2 == 0:
    print ("El número %s es par" %numero)
else:
    print ("El número %s es impar" %numero)

El número 16 es par


### 1.3 Combinación de estructuras de código

Las estructuras de loops vistas en el notebook anterior, y los condicionales revisados en este notebook se pueden combinar para generar comportamientos más complejos. Supongamos que tenemos una lista de edades y queremos dejar aquellas que sean mayores que 18 años. Esto se puede lograr de la siguiente forma:

In [1]:
lista_de_edades = [4,20,15,29,11,42,10,18]
lista_mayores = []

for edad in lista_de_edades:
    if (edad >= 18):
        # Agregamos a la lista de mayores
        lista_mayores.append(edad)

print(lista_mayores)

[20, 29, 42, 18]


### 1.4 Operaciones lógicas y estructuras de control

A veces hay que ejecutar una línea de código si se cumple más de una condición. Esto se puede lograr fácilmente usando las operaciones lógicas que ya estudiadas. Supongamos que tenemos una lista de números, y queremos seleccionar aquellos que cumplan ciertas condiciones. Ejemplo: que son mayores o iguales que 5 y menores que 20. Esto se puede lograr de la siguiente forma:

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5:
        if numero < 20:
            seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


**Notar** que los números seleccionados cumplen los requisitos, pero hay formas alternativa de hacerlo. Por ejemplo:

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5 and numero < 20:
        seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


El resultado es el mismo. Si bien esta forma es más compacta, no necesariamente es mejor. Se sugiere trabajar como lo vean más simple. Si ambas condiciones juntas son difíciles de leer, entonces se puedes usar la primera forma.

<font color='mediumblue'>**Ejercicio:**</font> Modifica el ejemplo anterior para que seleccione aquellos números **mayores** que 5 **o** impares.

In [ ]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero > 5 or numero%2 != 0:
        seleccionados.append(numero)
print(seleccionados)

[3, 1, 6, 17, 3, 89, 5, 6, 13, 25, 3, 23, 1, 15]


## <font color='mediumblue'>Ejercicios</font>

<font color='mediumblue'>**Ejercicio 1:**</font> ¿Qué pasa al sumar, restar, multiplicar o dividir booleanos? Probarlo e interpretar.

In [ ]:
print(True + True)
print(True + False)
# COMPLETAR

2
1


<font color='mediumblue'>**Ejercicio 2:**</font> Hacer una estructura `if/else` que compare dos variables numéricas `A` y `B`, y  decida cuál es mayor. Luego que imprima en pantalla "A es mayor que B" o "B es mayor que A" . 

In [2]:
A = 5
B = 4

if B < A:
  print("A es mayor que B")
elif B > A:
  print("B es mayor que A")
else:
  print("A y B son iguales")

A es mayor que B


<font color='mediumblue'>**Ejercicio 3:**</font> Dada la siguiente lista de numeros:

In [ ]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]

Escribir un código que calcule la suma de los números **pares menores que 5** en esta lista. **Pistas:** 
* Hay varias formas de hacerlo. Está bien si trabajar más de una. Pero se sugiere tomar los ejemplos vistos en el notebook.
* El resultado es 20. 
* Recuerdar que se puede inicializar una variable en cero, y luego ir modificándola en un loop. Algo así se hizo en el notebook anterior (ejercicio 5) con una variable llamada `i`.

In [ ]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]
numeros_2 = [] # crea una lista vacía

for item in numeros: # define item como cada elemento de la lista
    if (item %2 == 0) and item < 5: # parámetro de comparación
        numeros_2.append(item) # agrega los datos que cumplen con el parámetro

print(numeros_2)
sum(numeros_2)

[4, 4, 4, 2, 2, 4]


20

<font color='mediumblue'>**Ejercicio 4**</font> - **Opcional:** Dada la siguiente lista de numeros:

In [ ]:
numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1', '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
print(numeros_en_texto)

['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1',

Calcule la suma de los unos (1) y los tres (3) en esta lista. Nuevamente, hay muchas formas de hacerlo. **Pistas:** 
* El resultado es 210.
* Se puede reciclar código de ejemplos anteriores y del ejercicio anterior.
* Se pueden comparar strings (ver ejemplo más arriba).
* También se pueden forzar tipos de datos. Por ejemplo, `int('4')` devuelve un 4 como entero.
* Se puede resolver sin usar todas las pistas

In [ ]:
Suma_de_1 = numeros_en_texto.count('1')*1
Suma_de_3 = numeros_en_texto.count('3')*3

print(Suma_de_1 + Suma_de_3)

210


## 2. Numpy

Para usar una librería, primero hay que instalarla. Luego importarla.

Cómo instalar una librería?

Todas las librerías tienen una documentación. La documentación de Numpy se puede ver [aquí](https://numpy.org/doc/).

Qué es importar una librería? Es avisarle a Python que se usarán funciones asociadas a esa librería. Numpy se importa con la siguiente línea de código:

In [5]:
import numpy as np

Ahora el ambiente de trabajo sabe que si ponemos algo del estilo `np.` significa que esa funcionalidad la debe buscar en NumPy. **Ojo:** Si la librería NO se instaló correctamente, saldrá un mensaje de error.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas y, de hecho, se pueden crear a partir de ellas.

In [5]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. Recordemos que sumarle un número a toda la lista no estaba permitido

In [6]:
lista + 1

TypeError: can only concatenate list (not "int") to list

¡Pero ahora con los arreglos sí!

In [7]:
arreglo + 1

array([1, 2, 3, 4, 5, 6])

Esto simplifica mucho hacer cuentas. Pero no es sólo sumar, también muchas otras operaciones:

In [ ]:
print(arreglo - 5)
print(arreglo - 2)
print(arreglo*4)
print(arreglo**2)

[-5 -4 -3 -2 -1  0]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso de una lista?

### 2.1 Creación de arreglos

Si bien es posible crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo.

Una muy utilizada es `np.arange()`. Se sugiere consultar su documentación en la web. Otra opción de ver documentación (o help) es escribiend en una celda de código `np.arange` + `shift` + `tab`, . De esa forma, aparecerá la ayuda.

Ejemplo:

In [6]:
arreglo = np.arange(3,20,2)
print(arreglo)

[ 3  5  7  9 11 13 15 17 19]


<font color='mediumblue'>**Ejercicio:**</font> investigar y crear ejemplos con las funciones
* `np.linspace`. Diferenciar de `np.arange`.
* `np.zeros` y `np.ones`

### 2.2 Shape de los arreglos

Los arreglos tienen muchas más propiedades que las listas. En particular, pueden tener más de un *eje* o dimensión. Veamos a qué nos referimos:

In [ ]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


Notar que `arreglo_2d` tiene dos filas y cuatro columnas. Esto se puede ver usando la propiedad `.shape` del arreglo.

In [ ]:
print(arreglo_2d.shape)

(2, 4)


Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`? Otro ejemplo:

In [7]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Para saber cuántos elementos tiene, se puede usar `.size`

In [8]:
print(arreglo_2d.size)

8


### 2.3 Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un bastantes de funciones que operan sobre los arreglos. Veamos algunos ejemplos.

In [9]:
un_arreglo = np.array([-100,2,3,17,25,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-100
95


En el caso 2D, es posible pedir que estas funciones operen sobre todo el arreglo, o por ejes.



In [11]:
arreglo_2d = np.arange(9) # genera un arreglo de 9 elementos
np.random.shuffle(arreglo_2d) # reordena de forma random el arreglo completo
arreglo_2d = arreglo_2d.reshape((3,3)) # lo ordena como 3x3
print(arreglo_2d)

[[1 4 2]
 [0 8 5]
 [6 3 7]]


**Ojo:** tratar de entender la diferencia entre las siguientes instrucciones.

In [25]:
print(arreglo_2d.max()) # recorre toda la matriz
print(arreglo_2d.max(axis = 0)) # axis 0: va en dirección de columnas
print(arreglo_2d.max(axis = 1)) # axis 1: va fila por fila

8
[7 8 5]
[6 8 3]


### Comentarios finales

Indexado / slicing:
- Para arreglos 1D es similar que para la listas.
- Para arreglos 2D es diferente. Para estudiarlo se sugiere jugar con la siguiente celda:

In [30]:
arreglo_2d = np.arange(9).reshape(3,3)
print(arreglo_2d)
print(arreglo_2d[1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


* Es posible usar `arreglo.max()` o `np.max(arreglo)`. Esto no solo es válido para la función `max()`, también para casi todas las funciones que operen sobre arreglos. 

In [12]:
print(np.min(un_arreglo), un_arreglo.min())

-100 -100


Existe mucho más para estudiar sobre NumPy. A medida que se necesite, se verán más funcionalidades.

## <font color='mediumblue'>Ejercicios</font>

<font color='mediumblue'>**Ejercicio 1:**</font> Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`

In [15]:
n = np.linspace(0.0, 9.0, num=100)
print(n)
print(len(n))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

<font color='mediumblue'>**Ejercicio 2:**</font> crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [28]:
m = np.zeros(20,dtype=int)
print(m)
print(len(m))
print(m.ndim)
m[:14] = 1
print(m)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
20
1
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]


<font color='mediumblue'>**Ejercicio 3:**</font> crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [27]:
x = np.zeros(50,dtype=int)
print(x)
print(len(x))
print(x.ndim)
x[:25] = np.arange(25)
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
50
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0]


<font color='mediumblue'>**Ejercicio 4:**</font> crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [4]:
s = np.zeros(9,dtype=int).reshape(3,3)
print(s)
print(s[:,1:2])
t = np.arange(1,4,dtype=int).reshape(3,1)
print(t)
s[:,1:2] = t
print(s)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0]
 [0]
 [0]]
[[1]
 [2]
 [3]]
[[0 1 0]
 [0 2 0]
 [0 3 0]]


<font color='mediumblue'>**Ejercicio 5:**</font> crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [123]:
q = np.zeros(9,dtype=int).reshape(3,3)
print(q)
print(q.ndim)
print(len(q))
for i in range(len(q)):
    q[i][i] = 1
print(q)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
2
3
[[1 0 0]
 [0 1 0]
 [0 0 1]]


<font color='mediumblue'>**Ejercicio 6:**</font> crear un arreglo 2D de 100 filas y 100 columnas lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0 
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```

In [128]:
z = np.zeros(10000,dtype=int).reshape(100,100)
print(z)
print(z.ndim)
print(len(z))
for i in range(len(z)):
    z[i][i] = 1
print(z)

#w = np.ones(100,dtype=int) # generar lista con los valores que quiero en la diagonal principal
#print(w)
#z2 = np.diagflat(w) # generar matriz con w como diagonal principal y el resto en ceros
#print(z2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2
100
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


<font color='crimson'>**Extra:**</font> ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?¿Y si queremos cambiarle el tipo de dato, por ejemplo a `int`? Googlear "numpy astype". ¿Qué pasa si usamos `astype(bool)`?

In [8]:
# creo que por defecto son float64
import numpy as np
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [9]:
x = x.astype(int)
x

array([1, 2, 2])